---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-migration.html 
summary: Dieser Abschnitt enthält Details zu Faktoren, die bei der Migration einer Oracle-Datenbank von lokalen Standorten zu einer AWS EC2-Instanz und einem FSx-Speicher berücksichtigt werden müssen. 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= Datenbankmigration von On-Premise in die Public Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Datenbankmigration ist in jedem Fall ein anspruchsvolles Unterfangen.  Die Migration einer Oracle-Datenbank von einem lokalen Standort in die Cloud ist keine Ausnahme.

In den folgenden Abschnitten werden die wichtigsten Faktoren beschrieben, die bei der Migration von Oracle-Datenbanken in die öffentliche AWS-Cloud mit der AWS EC2-Rechen- und FSx-Speicherplattform zu berücksichtigen sind.



== ONTAP -Speicher ist vor Ort verfügbar

Wenn sich die lokale Oracle-Datenbank auf einem ONTAP -Speicherarray befindet, ist es einfacher, die Replikation für die Datenbankmigration mithilfe der in den AWS FSx ONTAP -Speicher integrierten NetApp SnapMirror -Technologie einzurichten.  Der Migrationsprozess kann mithilfe der NetApp BlueXP Konsole orchestriert werden.

. Erstellen Sie eine EC2-Ziel-Compute-Instanz, die der lokalen Instanz entspricht.
. Stellen Sie passende, gleich große Datenbankvolumes über die FSx-Konsole bereit.
. Mounten Sie die FSx-Datenbankvolumes in der EC2-Instance.
. Richten Sie die SnapMirror Replikation zwischen den lokalen Datenbankvolumes und den Ziel-FSx-Datenbankvolumes ein.  Die erste Synchronisierung zum Verschieben der primären Quelldaten kann einige Zeit in Anspruch nehmen, alle nachfolgenden inkrementellen Aktualisierungen erfolgen jedoch viel schneller.
. Beenden Sie zum Zeitpunkt der Umschaltung die primäre Anwendung, um alle Transaktionen zu stoppen.  Führen Sie über die Oracle sqlplus CLI-Schnittstelle einen Oracle-Online-Protokollwechsel aus und lassen Sie SnapMirror Sync das letzte archivierte Protokoll auf das Zielvolume übertragen.
. Teilen Sie die gespiegelten Volumes auf, führen Sie die Oracle-Wiederherstellung auf dem Ziel aus und starten Sie die Datenbank für den Dienst.
. Richten Sie Anwendungen auf die Oracle-Datenbank in der Cloud aus.


Das folgende Video zeigt, wie Sie eine Oracle-Datenbank mithilfe der NetApp BlueXP -Konsole und der SnapMirror Replikation von vor Ort zu AWS FSx/EC2 migrieren.

.Migrieren Sie lokale Oracle-Datenbanken zu AWS
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto]


== ONTAP -Speicher ist vor Ort nicht verfügbar

Wenn die lokale Oracle-Datenbank auf einem anderen Speicher eines Drittanbieters als ONTAP gehostet wird, basiert die Datenbankmigration auf der Wiederherstellung einer Sicherungskopie der Oracle-Datenbank.  Sie müssen das Archivprotokoll abspielen, um es vor dem Umschalten auf den neuesten Stand zu bringen.

AWS S3 kann als Staging-Speicherbereich für die Datenbankverschiebung und -migration verwendet werden.  Beachten Sie die folgenden allgemeinen Schritte für diese Methode:

. Stellen Sie eine neue, passende EC2-Instanz bereit, die mit der lokalen Instanz vergleichbar ist.
. Stellen Sie gleiche Datenbankvolumes aus dem FSx-Speicher bereit und mounten Sie die Volumes in die EC2-Instance.
. Erstellen Sie eine Oracle-Sicherungskopie auf Festplattenebene.
. Verschieben Sie die Sicherungskopie in den AWS S3-Speicher.
. Erstellen Sie die Oracle-Steuerdatei neu und stellen Sie die Datenbank wieder her, indem Sie Daten und das Archivprotokoll aus dem S3-Speicher abrufen.
. Synchronisieren Sie die Ziel-Oracle-Datenbank mit der lokalen Quelldatenbank.
. Fahren Sie beim Umschalten die Anwendung und die Oracle-Quelldatenbank herunter.  Kopieren Sie die letzten Archivprotokolle und wenden Sie sie auf die Ziel-Oracle-Datenbank an, um sie auf den neuesten Stand zu bringen.
. Starten Sie die Zieldatenbank für den Benutzerzugriff.
. Leiten Sie die Anwendung zur Zieldatenbank um, um die Umstellung abzuschließen.




== Migrieren Sie lokale Oracle-Datenbanken mithilfe der PDB-Verlagerung mit maximaler Verfügbarkeit zu AWS FSx/EC2

Dieser Migrationsansatz eignet sich am besten für Oracle-Datenbanken, die bereits im PDB/CDB-Multitenant-Modell bereitgestellt werden und für die vor Ort kein ONTAP Speicher verfügbar ist.  Die PDB-Verlagerungsmethode nutzt die Oracle PDB-Hot-Clone-Technologie, um PDBs zwischen einer Quell-CDB und einer Ziel-CDB zu verschieben und dabei die Dienstunterbrechung zu minimieren.

Erstellen Sie zunächst eine CDB in AWS FSx/EC2 mit ausreichend Speicherplatz, um PDBs zu hosten, die von vor Ort migriert werden sollen.  Mehrere lokale PDBs können einzeln verschoben werden.

. Wenn die lokale Datenbank in einer einzelnen Instanz und nicht im mehrinstanzenfähigen PDB/CDB-Modell bereitgestellt wird, befolgen Sie die Anweisungen inlink:azure-ora-nfile-migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["Konvertieren einer einzelnen Instanz einer Nicht-CDB in eine PDB in einer Multitenant-CDB"^] um die einzelne Instanz in eine Multitenant-PDB/CDB zu konvertieren.  Folgen Sie dann dem nächsten Schritt, um das konvertierte PDB in AWS FSx/EC2 in CDB zu migrieren.
. Wenn die lokale Datenbank bereits im Multitenant-PDB/CDB-Modell bereitgestellt ist, folgen Sie den Anweisungen inlink:azure-ora-nfile-migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["Migrieren Sie lokale Oracle-Datenbanken mit PDB-Verlagerung in die Cloud"^] um die Migration durchzuführen.


Das folgende Video zeigt, wie eine Oracle-Datenbank (PDB) mithilfe der PDB-Relocation mit maximaler Verfügbarkeit nach FSx/EC2 migriert werden kann.

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["Migrieren Sie lokale Oracle PDBs mit maximaler Verfügbarkeit zu AWS CDB"^]


NOTE: Obwohl die Anweisungen in Schritt 1 und 2 im Kontext der öffentlichen Azure-Cloud dargestellt werden, sind die Verfahren ohne Änderungen auf die AWS-Cloud anwendbar.

Das NetApp Solutions Automation-Team bietet ein Migrations-Toolkit, das die Migration von Oracle-Datenbanken von lokalen Standorten in die AWS-Cloud erleichtern kann.  Verwenden Sie den folgenden Befehl, um das Oracle-Datenbankmigrations-Toolkit für die PDB-Verschiebung herunterzuladen.

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----