---
sidebar: sidebar 
permalink: oracle/tr-4250.html 
keywords:  
summary:  
---
= TR-4250: SAP mit Oracle unter UNIX und NFS mit NetApp Clustered Data ONTAP und SnapManager für SAP 3.4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Nils Bauer, NetApp

[role="lead"]
TR-4250 befasst sich mit den Herausforderungen bei der Entwicklung von Speicherlösungen zur Unterstützung von SAP Business Suite-Produkten mithilfe einer Oracle-Datenbank.  Der Schwerpunkt dieses Dokuments liegt auf den allgemeinen Herausforderungen bei der Konzeption, Bereitstellung, dem Betrieb und der Verwaltung von Speicherinfrastrukturen, mit denen Geschäfts- und IT-Leiter konfrontiert sind, die die neueste Generation von SAP-Lösungen verwenden.  Die Empfehlungen in diesem Dokument sind allgemeiner Natur; sie beziehen sich nicht speziell auf eine SAP-Anwendung oder auf die Größe und den Umfang der SAP-Implementierung.  TR-4250 setzt voraus, dass der Leser über ein grundlegendes Verständnis der Technologie und des Betriebs von NetApp und SAP-Produkten verfügt.  TR-4250 wurde auf Grundlage der Interaktion zwischen technischen Mitarbeitern von NetApp, SAP, Oracle und unseren Kunden entwickelt.

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["TR-4250: SAP mit Oracle unter UNIX und NFS mit NetApp Clustered Data ONTAP und SnapManager für SAP 3.4"^]
