= Wo bekomme ich Hilfe?
:allow-uri-read: 


. Melden Sie sich als Oracle-Benutzer beim Oracle-Server an und führen Sie die folgenden Befehle aus:
+
[source, cli]
----
ps -ef | grep ora
----
+

NOTE: Hier werden Oracle-Prozesse aufgelistet, wenn die Installation wie erwartet abgeschlossen und Oracle DB gestartet wurde.

. Melden Sie sich bei der Datenbank an, um die Datenbankkonfigurationseinstellungen und die mit den folgenden Befehlssätzen erstellten PDBs zu überprüfen.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL>

SQL> select name, log_mode from v$database;
NAME      LOG_MODE
--------- ------------
CDB2      ARCHIVELOG

SQL> show pdbs

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO

col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;

SQL> col svrname form a30
SQL> col dirname form a30
SQL> select svrname, dirname, nfsversion from v$dnfs_servers;

SVRNAME                        DIRNAME                        NFSVERSION
------------------------------ ------------------------------ ----------------
172.21.126.200                 /rhelora03_u02                 NFSv3.0
172.21.126.200                 /rhelora03_u03                 NFSv3.0
172.21.126.200                 /rhelora03_u01                 NFSv3.0
----
+
Dies bestätigt, dass dNFS ordnungsgemäß funktioniert.

. Stellen Sie über den Listener eine Verbindung zur Datenbank her, um die Oracle-Listener-Konfiguration mit dem folgenden Befehl zu überprüfen.  Wechseln Sie zum entsprechenden Listener-Port und Datenbankdienstnamen.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 13:19:57 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Wed May 05 2021 17:11:11 -04:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL> show user
USER is "SYSTEM"
SQL> show con_name
CON_NAME
CDB2_PDB1
----
+
Dies bestätigt, dass der Oracle-Listener ordnungsgemäß funktioniert.





=== Wo bekomme ich Hilfe?

Wenn Sie Hilfe mit dem Toolkit benötigen, treten Sie bitte dem beilink:https://netapppub.slack.com/archives/C021R4WC0LC["Slack-Kanal für den Community-Support von NetApp Solution Automation"] und suchen Sie nach dem Kanal zur Lösungsautomatisierung, um Ihre Fragen oder Anfragen zu posten.
