---
sidebar: sidebar 
permalink: mysql/tr-4722.html 
keywords:  
summary:  
---
= TR-4722: MySQL-Datenbank auf NetApp ONTAP – Best Practices
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Anup Bharti, Manohar Kulkarni, Jeffrey Steiner NetApp

[role="lead"]
MySQL und seine Varianten, einschließlich MariaDB und Percona, werden häufig für viele Unternehmensanwendungen verwendet.  Diese Anwendungen reichen von globalen sozialen Netzwerken und riesigen E-Commerce-Systemen bis hin zu SMB-Hosting-Systemen mit Tausenden von Datenbankinstanzen.  Dieses Dokument beschreibt die Konfigurationsanforderungen und bietet Anleitungen zur Optimierung und Speicherkonfiguration für die Bereitstellung von MySQL auf der Datenverwaltungssoftware NetApp ONTAP .  Um festzustellen, ob die in diesem Bericht angegebene Umgebung, Konfigurationen und Versionen Ihre Umgebung unterstützen, konsultieren Sie das Interoperability Matrix Tool (IMT).

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["TR-4722: MySQL-Datenbank auf NetApp ONTAP – Best Practices"^]
