---
sidebar: sidebar 
permalink: automation/marketing-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Auf dieser Seite wird die automatisierte Methode zum Bereitstellen von Oracle19c auf NetApp ONTAP -Speicher beschrieben. 
---
= Lösungsübersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Auf dieser Seite wird die automatisierte Methode zum Bereitstellen von Oracle19c auf NetApp ONTAP -Speicher beschrieben.



[[automated-deployment-of-oracle19c-for-ontap-on-nfs]]
== Automatisierte Bereitstellung von Oracle19c für ONTAP auf NFS

Organisationen automatisieren ihre Umgebungen, um die Effizienz zu steigern, Bereitstellungen zu beschleunigen und den manuellen Aufwand zu reduzieren.  Konfigurationsmanagement-Tools wie Ansible werden verwendet, um den Datenbankbetrieb in Unternehmen zu optimieren.  In dieser Lösung zeigen wir, wie Sie mit Ansible die Bereitstellung und Konfiguration von Oracle 19c mit NetApp ONTAP automatisieren können.  Indem Sie Speicheradministratoren, Systemadministratoren und Datenbankadministratoren die Möglichkeit geben, konsistent und schnell neuen Speicher bereitzustellen, Datenbankserver zu konfigurieren und Oracle 19c-Software zu installieren, erzielen Sie die folgenden Vorteile:

* Beseitigen Sie komplexe Designs und menschliche Fehler und implementieren Sie eine wiederholbare, konsistente Bereitstellung und bewährte Methoden.
* Reduzieren Sie die Zeit für die Bereitstellung von Speicher, die Konfiguration von DB-Hosts und die Oracle-Installation
* Steigern Sie die Produktivität von Datenbankadministratoren, System- und Speicheradministratoren
* Ermöglichen Sie die Skalierung von Speicher und Datenbanken mit Leichtigkeit


NetApp stellt Kunden validierte Ansible-Module und -Rollen zur Verfügung, um die Bereitstellung, Konfiguration und Lebenszyklusverwaltung Ihrer Oracle-Datenbankumgebung zu beschleunigen.  Diese Lösung bietet Anweisungen und Ansible-Playbook-Code, um Ihnen zu helfen:

* Erstellen und Konfigurieren von ONTAP NFS-Speicher für Oracle Database
* Installieren Sie Oracle 19c auf RedHat Enterprise Linux 7/8 oder Oracle Linux 7/8
* Konfigurieren Sie Oracle 19c auf ONTAP NFS-Speicher


Weitere Einzelheiten oder den Einstieg finden Sie in den Übersichtsvideos unten.



[[awxtower-deployments]]
=== AWX/Tower-Bereitstellungen

Teil 1: Erste Schritte, Anforderungen, Automatisierungsdetails und anfängliche AWX/Tower-Konfiguration

.AWX-Bereitstellung
video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto]
Teil 2: Variablen und Ausführen des Playbooks

.AWX Playbook-Ausführung
video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto]


[[cli-deployment]]
=== CLI-Bereitstellung

Teil 1: Erste Schritte, Anforderungen, Automatisierungsdetails und Einrichtung des Ansible Control Hosts

.CLI-Bereitstellung
video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto]
Teil 2: Variablen und Ausführen des Playbooks

.CLI-Playbook-Ausführung
video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto]